S02US12
WildCodeSchool/orleans-202109-php-projet-apclo pull request #114
Opened 2021-11-10 22:50 UTC by Nitram-Edurel

2021-11-11 09:50 UTC, WeisgerberEstelle requested changes

2021-11-11 09:50 UTC, WeisgerberEstelle commented on src/View/Association/index.html.twig
> +</div></div></div>{% endblock %}
Attention faute de frappe sur secrétaire!

2021-11-11 09:50 UTC, WeisgerberEstelle commented on public/assets/css/form.css
> +}
Oublie pas d'utiliser var(--spacing2) pour des margin/padding de 15px

2021-11-11 11:43 UTC, ThibaultFoure requested changes
Derniers petits ajustements et c'est ok 😉

2021-11-11 11:43 UTC, ThibaultFoure commented on public/assets/css/asso.css
> +
Des lignes vides ici

2021-11-11 11:43 UTC, ThibaultFoure commented on public/assets/css/style.css
> +    --border-radius     : 8px;
utilise le --spacing pour 8px c'est la valeur de base

2021-11-11 14:35 UTC, ThibaultFoure commented on src/View/Association/index.html.twig
> +</div>{% endblock %}
Si je voulais chipoter (oui, chipoter) et je vais le faire, petit retour à la ligne manquant après la div

2021-11-11 16:05 UTC, ThibaultFoure commented on src/View/Association/index.html.twig
> +</div>{% endblock %}
Je voulais dire comme ça 
```suggestion
</div>
{% endblock %}
```

2021-11-11 17:34 UTC, Nitram-Edurel commented on src/View/Association/index.html.twig
> +</div>{% endblock %}
Ah d'accord, c'est le formateur qui me la positionné comme ça

2021-11-11 18:10 UTC, ThibaultFoure submitted a review, later dismissed
C'est oui

2021-11-12 09:25 UTC, sblondeau approved these changes

2021-11-15 18:59 UTC, ThibaultFoure requested changes
Des petits ajustements et c'est ok :)

2021-11-15 18:59 UTC, ThibaultFoure commented on public/assets/css/asso.css
> +@import url('style.css');
A supprimer, c'est ce fichier qu tu importes dans le css principal, pas l'inverse :wink: 
La ligne vide en dessous aussi du coup

2021-11-15 18:59 UTC, ThibaultFoure commented on public/assets/css/style.css
> +
petite ligne vide ici

2021-11-16 12:37 UTC, ThibaultFoure approved these changes

2021-11-16 12:37 UTC, ThibaultFoure approved these changes

2021-11-16 12:59 UTC, sblondeau approved these changes

2021-11-16 12:59 UTC, merged