S02 us23 addactuality
WildCodeSchool/orleans-202109-php-projet-apclo pull request #119
Opened 2021-11-12 00:39 UTC by Djoasiong

2021-11-12 11:50 UTC, WeisgerberEstelle requested changes

2021-11-12 11:50 UTC, WeisgerberEstelle commented on public/assets/css/admin-actuality-form.css
> +    --spacing1: 8px;
il existe deja dans style.css il s'appelle --spacing
dailleurs border-radius aussi

2021-11-12 11:50 UTC, WeisgerberEstelle commented on public/assets/css/admin-actuality-form.css
> +}
tu peux pas définir box-shadow avec --spacing1 il lui faut 4 parametres

2021-11-12 11:50 UTC, WeisgerberEstelle commented on public/assets/css/style-admin.css
> +}
C'est pas très opti de définir la taille d'un texte avec la taille d'un espacement
car i tu changes tes espacements le texte va changer aussi

2021-11-12 11:58 UTC, ThibaultFoure requested changes

2021-11-12 11:58 UTC, ThibaultFoure commented on public/assets/css/admin-actuality-form.css
> +    --spacing2: 150px;
Attention, tu n'as pas besoin de redéfinir un --spacing de 8px, utilise plutôt celui du style.css, et si tu définis un --spacing de 150px nomme le spécifiquement pour cette partie, sinon il risque d'entrer en conflit avec --spacing2 de style.css
Et si tu définis des variables que tu utilises plusieurs fois, il vaut mieux les définir dans :root au début de ton fichier :wink:

2021-11-12 11:58 UTC, ThibaultFoure commented on public/assets/css/admin-actuality.css
> +    --spacing2: 60px;
Pareil que sur ton autre fichier, il vaudrait mieux déplacer tes variables dans :root et les nommer plus explicitement

2021-11-12 11:58 UTC, ThibaultFoure commented on public/assets/css/admin-actuality.css
> +    height: 8px;
var(--spacing2) :wink:

2021-11-12 11:58 UTC, ThibaultFoure commented on src/Controller/AdminActualityController.php
> +                $errors[] = 'Le champs titre est obligatoire';
Le champ *

2021-11-12 11:58 UTC, ThibaultFoure commented on src/Controller/AdminActualityController.php
> +                $errors[] = 'Le titre doit faire moins de' . $maxTitleLength . 'caractères.';
Ajout des espaces après le de -> moins de' et avant caractères -> 'caractères.
Sinon l'erreur affichera "Le titre doit faire moins de255caractères."

2021-11-12 11:58 UTC, ThibaultFoure commented on src/Controller/AdminActualityController.php
> +                $errors[] = 'Le champs date est obligatoire';
champ

2021-11-12 11:58 UTC, ThibaultFoure commented on src/View/Admin/Actuality/index.html.twig
> +
ligne vide

2021-11-12 11:58 UTC, ThibaultFoure commented on public/assets/css/style-admin.css
> +    --text-size         : var(--spacing3);
Ca n'a pas vraiment de sens de définir une variable qui est égale à une autre variable, autant l'utiliser directement

2021-11-12 12:04 UTC, Djoasiong commented on public/assets/css/admin-actuality-form.css
> +    --spacing2: 150px;
pas de conflit s'il est propre à mon fichier et non dans root

2021-11-12 14:09 UTC, ArtGouaux submitted a review, later dismissed

2021-11-15 08:16 UTC, sblondeau requested changes
j'ai l'index et le add dans la meme PR, donc 2 US en une, non ?
à redécouper

2021-11-15 08:16 UTC, sblondeau commented on src/Controller/AdminActualityController.php
> +            if (empty($actuality['date'])) {
vérifier aussi que c'est une date valide

2021-11-15 19:09 UTC, ThibaultFoure approved these changes
C'est ok pour moi Djoa qui n'est pas un gars :sweat_smile:

2021-11-16 08:01 UTC, sblondeau approved these changes

2021-11-16 08:01 UTC, merged