S02 us25 edit actuality
WildCodeSchool/orleans-202109-php-projet-apclo pull request #121
Opened 2021-11-12 11:39 UTC by Djoasiong

2021-11-14 11:05 UTC, WeisgerberEstelle requested changes

2021-11-14 11:05 UTC, WeisgerberEstelle commented on public/assets/css/style.css
>      --height-image-card : calc(var(--height-card) / 2.1);
Pas sur que le chiffre 2.1 passe j'ai eu le meme soucis avec mes cards, il faut un calcul qui se base sur quelque chose de concret et non sur des nombres magiques

2021-11-14 11:05 UTC, WeisgerberEstelle commented on public/assets/css/style.css
>      --border-radius     : 8px;
ya pas une variable sur root pour le border radius = 8px?

2021-11-14 11:05 UTC, WeisgerberEstelle commented on src/View/Admin/Actuality/add.html.twig
> +{% endblock %}
le add ne fait pas partie de cet US

2021-11-14 11:05 UTC, WeisgerberEstelle commented on src/Model/ActualityManager.php
> +    }
Tu as 2 users stories

2021-11-14 11:05 UTC, WeisgerberEstelle commented on src/routes.php
>      'items/add' => ['ItemController', 'add',],
Plusieurs users stories

2021-11-14 11:11 UTC, Djoasiong commented on src/routes.php
>      'items/add' => ['ItemController', 'add',],
j'ai copié les autres US pour pouvoir continuer le CRUD

2021-11-16 15:01 UTC, Nitram-Edurel approved these changes

2021-11-16 15:03 UTC, sblondeau requested changes

2021-11-16 15:03 UTC, sblondeau commented on public/assets/css/style.css
>      --height-image-card : calc(var(--height-card) / 2.1);
+1

2021-11-16 15:03 UTC, sblondeau commented on src/routes.php
> +    'admin/actualités/éditer' => ['AdminActualityController', 'edit', ['id']],
pas d'accent

2021-11-16 15:03 UTC, sblondeau commented on src/routes.php
>      'items/add' => ['ItemController', 'add',],
ce n'est pas une bonne idée car si l'autre US que tu copie et qui n'est pas validée a des erreurs, tu les retraines ici alors que tu les aurais corrigé sur l'autre

2021-11-16 15:54 UTC, sblondeau approved these changes

2021-11-16 15:54 UTC, merged