S02 us19 create editing form
WildCodeSchool/orleans-202109-php-projet-apclo pull request #125
Opened 2021-11-12 16:58 UTC by WeisgerberEstelle

2021-11-14 11:02 UTC, Djoasiong submitted a review, later dismissed

2021-11-15 08:20 UTC, sblondeau requested changes

2021-11-15 08:20 UTC, sblondeau commented on src/Controller/AdminCatController.php
> +        if (empty($cat['birth_date'])) {
vérifier qu'on a bien un format de date valide

2021-11-15 08:20 UTC, sblondeau commented on src/View/Admin/Cat/_form.html.twig
> +					{% if (breed.name == cat.breed) or (breed.id == cat.breed_id) %}
non c'est juste sur l'id que tu check (l'attribut value de ton select); et pas sur breed.name
(idem pour tous tes selects)

2021-11-15 08:20 UTC, sblondeau commented on src/View/Admin/Cat/_form.html.twig
> +					{% if (breed.name == cat.breed) or (breed.id == cat.breed_id) %}
et le mieux serait que tu ne mettes la condition que autour du selected et pas répéter toute la ligne, tu peux utiliser une condition ternaire d'ailleurs dans ce cas pour faire plus concis, et pas la peine de mettre selected=selected, juste selected suffit
```
<option value="{{ breed.id }}" {{ breed.id == cat.breed_id ? 'selected' : '' }}>{{ breed.name }}</option>
```

2021-11-16 14:27 UTC, Djoasiong approved these changes

2021-11-16 14:49 UTC, sblondeau submitted a review, later dismissed

2021-11-16 14:49 UTC, ArtGouaux submitted a review, later dismissed

2021-11-16 15:23 UTC, Nitram-Edurel submitted a review, later dismissed

2021-11-16 16:13 UTC, Nitram-Edurel approved these changes

2021-11-16 16:25 UTC, merged