creation members cards
WildCodeSchool/orleans-202109-php-projet-apclo pull request #127
Opened 2021-11-14 19:43 UTC by ArtGouaux

2021-11-15 09:16 UTC, ThibaultFoure requested changes
Mouais

2021-11-15 09:16 UTC, ThibaultFoure commented on src/View/Association/index.html.twig
> +				<p>Le bureau est constitué d'un président, d'une vice-président, d'un secrétaire et d'un trésorier.</p>
d'une vice-présidentE si je ne m'abuse ?

2021-11-15 09:16 UTC, ThibaultFoure commented on src/View/Association/index.html.twig
> +
ligne vide

2021-11-15 09:16 UTC, ThibaultFoure commented on src/View/Association/index.html.twig
> +
ligne vide

2021-11-15 09:26 UTC, ThibaultFoure approved these changes

2021-11-15 09:49 UTC, sblondeau requested changes

2021-11-15 09:49 UTC, sblondeau commented on src/View/Association/_card.html.twig
> +<div class="container">
as mon avis, tu pourrais créer une table member et faire un selectAll dessus pour afficher les membres via une boucle, plutot que tout soit en dur
Meme si tu n'as pas le temps de faire un CRUD pour rendre ça administrable, tu aurais quelque chose d'un peu plus dynamique à moindre frais

2021-11-16 15:59 UTC, WeisgerberEstelle submitted a review, later dismissed

2021-11-16 16:00 UTC, Nitram-Edurel submitted a review, later dismissed

2021-11-16 23:32 UTC, sblondeau approved these changes

2021-11-16 23:32 UTC, merged