S02US15
WildCodeSchool/orleans-202109-php-projet-apclo pull request #128
Opened 2021-11-15 09:29 UTC by Nitram-Edurel

2021-11-15 09:31 UTC, ThibaultFoure commented on public/assets/css/form.css
> +
ligne vide encore

2021-11-15 09:31 UTC, ArtGouaux commented on public/assets/css/form.css
> +@import url('https://fonts.googleapis.com/css2?family=Bellota:wght@300;400;700&family=Handlee&display=swap');
Bin voyons

2021-11-15 09:34 UTC, ThibaultFoure commented on public/assets/css/form.css
> +    border-radius: var(--border-radius);
utilise -- spacing, Arthur est d'accord

2021-11-15 09:35 UTC, ThibaultFoure commented on public/assets/css/form.css
> +    border-radius: var(--border-radius);
utilise -- spacing, Arthur est d'accord

2021-11-15 09:36 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +        $errors = $stamp = [];
Pourquoi ? $stamp à suppr

2021-11-15 09:37 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +            if (empty($stamp['firstname'])) {
pourquoi stamp

2021-11-15 09:37 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +            if (strlen($stamp['lastname']) > $maxNameLength) {
pourquoi stamp

2021-11-15 09:38 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +            if (empty($stamp['lastname'])) {
pourquoi stamp

2021-11-15 09:38 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +            if (strlen($stamp['firstname']) > $maxNameLength) {
pourquoi stamp

2021-11-15 09:38 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +            if (empty($stamp['tel'])) {
pourquoi stamp

2021-11-15 09:38 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +            if (empty($stamp['email'])) {
pourquoi stamp

2021-11-15 09:39 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +        return $this->twig->render('Contact/Controller/index.html.twig', ['errors' => $errors, 'stamp' => $stamp]);
stamp

2021-11-15 09:39 UTC, ThibaultFoure commented on src/Model/StampManager.php
> +use OndraM\CiDetector\Ci\AbstractCi;
?

2021-11-15 09:40 UTC, ThibaultFoure commented on src/Model/StampManager.php
> +class StampManager extends AbstractManager
stamp

2021-11-15 09:40 UTC, ThibaultFoure commented on src/Model/StampManager.php
> +    public const TABLE = 'stamp';
stamp

2021-11-15 09:40 UTC, ThibaultFoure commented on src/Model/StampManager.php
> +    public function insert(array $stamp): int
stamp

2021-11-15 09:40 UTC, ThibaultFoure commented on src/Model/StampManager.php
> +        $statement->bindValue('title', $stamp['lastname'], \PDO::PARAM_STR);
staaaaaaaaaaaaaaaaaaaaaaaaaaamp

2021-11-15 09:42 UTC, ThibaultFoure commented on src/View/Contact/index.html.twig
> +					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"></header>
met col-12 directement, le reste est superflu

2021-11-15 09:42 UTC, ArtGouaux commented on public/assets/css/form.css
> +@import url('https://fonts.googleapis.com/css2?family=Bellota:wght@300;400;700&family=Handlee&display=swap');
Pas besoin si tu import notre style CSS

2021-11-15 09:42 UTC, ArtGouaux commented on public/assets/css/form.css
> +    display: inline-block;
Le diplay inline block n'est-il pas disponible avec Bootstrap directement ?

2021-11-15 09:42 UTC, ArtGouaux commented on src/Controller/ContactController.php
> +        $errors = $stamp = [];
Stamp..? STAMP ???? Un refuge pour timbres abandonnés peut-être ???

2021-11-15 09:42 UTC, ArtGouaux commented on src/View/Contact/index.html.twig
> +
Ligne vide

2021-11-15 09:42 UTC, ArtGouaux commented on src/View/Contact/index.html.twig
> +
Double lignes vides

2021-11-15 09:42 UTC, ArtGouaux commented on src/View/Contact/index.html.twig
> +
viiiiiide

2021-11-15 09:46 UTC, ThibaultFoure commented on src/View/Contact/index.html.twig
> +</html>{% endblock %}
```suggestion
</html>
{% endblock %}
```

2021-11-15 09:47 UTC, ThibaultFoure commented on src/View/Home/index.html.twig
> +
ligne vide + alignement

2021-11-15 21:37 UTC, Nitram-Edurel commented
J'ai mis en commentaire une partie du AdminContactController car je dois voire avec Sylvain concernant le "Npath complexity"

2021-11-16 08:14 UTC, WeisgerberEstelle approved these changes

2021-11-16 08:20 UTC, sblondeau requested changes

2021-11-16 08:20 UTC, sblondeau commented on src/Controller/AdminContactController.php
> +            /*$maxLastNameLength = 100;
pas de code commenté

2021-11-16 08:20 UTC, sblondeau commented on src/Controller/AdminContactController.php
> +            /*$maxLastNameLength = 100;
surtout si c'est pour faire passer la complexité... il faut que tu remettes le code et qu'on règle le pb ensuite

2021-11-16 08:20 UTC, sblondeau commented on src/Controller/AdminContactController.php
> +            $cat = array_map('trim', $_POST);
bah non, pas $cat... tu fais des copier / coller sans prendre de recul là... tu récupère un $contact, pas un $cat...

2021-11-16 08:36 UTC, closed without merging