S02 us24 delete actuality
WildCodeSchool/orleans-202109-php-projet-apclo pull request #139
Opened 2021-11-16 18:17 UTC by Djoasiong

2021-11-16 18:25 UTC, Nitram-Edurel approved these changes

2021-11-16 23:33 UTC, sblondeau requested changes

2021-11-16 23:33 UTC, sblondeau commented on src/Controller/AdminActualityController.php
> +            header('Location:/admin/actualités/index');
accent!

2021-11-16 23:33 UTC, sblondeau commented on src/routes.php
> +    'admin/actualités/supprimer' => ['AdminActualityController', 'delete',],
accent

2021-11-17 08:38 UTC, Nitram-Edurel approved these changes

2021-11-17 08:52 UTC, sblondeau approved these changes

2021-11-17 09:43 UTC, ArtGouaux approved these changes

2021-11-17 10:28 UTC, merged