FIX_US15
WildCodeSchool/orleans-202109-php-projet-apclo pull request #142
Opened 2021-11-16 20:27 UTC by Nitram-Edurel

2021-11-16 21:07 UTC, ArtGouaux approved these changes

2021-11-16 23:30 UTC, sblondeau requested changes

2021-11-16 23:30 UTC, sblondeau commented on src/Model/ContactManager.php
> +    public const TABLE = 'cat';
non table contact, pas cat !! 
je veux bien que tu le stock en bdd, mais ce form a pas forcément vocation à cela, un simple envoi de mail sans bdd serait suffisant. Vu le temps qu'il reste, je veux bien qu'on laisse comme ça, corrige juste le nom de la table !

2021-11-17 08:48 UTC, Djoasiong approved these changes

2021-11-17 09:06 UTC, sblondeau approved these changes

2021-11-17 09:06 UTC, merged