S1us07 display cat cards
WildCodeSchool/orleans-202109-php-projet-apclo pull request #36
Opened 2021-11-03 15:58 UTC by WeisgerberEstelle

Change name S1us07 name and png removed

2021-11-03 16:02 UTC, ThibaultFoure approved these changes

2021-11-03 16:46 UTC, sblondeau requested changes
non tu as tout pousser tes images sur la meme US... :( 
faut que ce soit sur une autre US là, et pas versionner les images de chat

2021-11-03 20:58 UTC, ThibaultFoure approved these changes

2021-11-04 08:07 UTC, sblondeau approved these changes

2021-11-04 08:07 UTC, merged