S01 us02
WildCodeSchool/orleans-202109-php-projet-apclo pull request #38
Opened 2021-11-03 18:12 UTC by Djoasiong

affichage bannière et texte
stylisation bannière, texte + responsive

2021-11-03 19:56 UTC, ThibaultFoure approved these changes

2021-11-04 08:40 UTC, sblondeau requested changes
une des images n'est pas utile pour ta PR, enlève là
pour l'image de la bannière, réduis le poids pour qu'elle fasse <200ko

2021-11-04 08:40 UTC, sblondeau commented on public/assets/css/banner.css
> +    background-image: url(/assets/images/cat-g6928c8fae_1280.jpg);
renomme ton image plus proprement. donc par ex cat_banner.jpg, qu'on puisse identifier tout de suite l'image

2021-11-04 08:40 UTC, sblondeau commented on public/assets/css/banner.css
> +    --width-background-color: 80%;
renomme mieux tes variables aussi, là width-background-color serait plutot width-banner-title (et dans la .banner ça serait plutot --width-banner )

2021-11-04 10:18 UTC, ThibaultFoure submitted a review, later dismissed

2021-11-04 10:22 UTC, WeisgerberEstelle submitted a review, later dismissed

2021-11-04 11:00 UTC, ThibaultFoure submitted a review, later dismissed

2021-11-04 11:24 UTC, sblondeau approved these changes

2021-11-04 11:32 UTC, ThibaultFoure approved these changes

2021-11-04 11:34 UTC, merged