S01 us01 navbar
WildCodeSchool/orleans-202109-php-projet-apclo pull request #44
Opened 2021-11-04 14:27 UTC by ArtGouaux

Notre Père, qui êtes aux cieux...

2021-11-04 14:41 UTC, ThibaultFoure approved these changes

2021-11-04 15:16 UTC, sblondeau requested changes

2021-11-04 15:16 UTC, sblondeau commented on src/View/Item/_navbar.html.twig
> +				<a class="nav-link" href="#"><img id="catHouseSvg" src="assets/images/cathouse.png" class="catHouseSvg"/>
tu ne les as pas en SVG tes icones plutot ? si oui c'est mieux, je pense qu'Estelle en a utiliser plusieurs qui sont redondantes avec les images utilisées ici, voit avec elle.

2021-11-04 15:58 UTC, Djoasiong approved these changes

2021-11-04 15:59 UTC, ThibaultFoure approved these changes

2021-11-04 16:25 UTC, sblondeau requested changes
ok reste plus qu'à supprimer les png qui sont tjs là ;-)

2021-11-05 08:43 UTC, ThibaultFoure approved these changes

2021-11-05 09:09 UTC, sblondeau approved these changes

2021-11-05 09:18 UTC, merged