S01 us10 display one catcard
WildCodeSchool/orleans-202109-php-projet-apclo pull request #51
Opened 2021-11-05 08:15 UTC by WeisgerberEstelle

2021-11-05 08:17 UTC, Djoasiong submitted a review, later dismissed

2021-11-05 08:18 UTC, ArtGouaux submitted a review, later dismissed

2021-11-05 09:24 UTC, sblondeau requested changes
tjs des images dans assets/images/uploads et non dans public/uploads

2021-11-05 09:24 UTC, sblondeau commented on database.sql
> +<<<<<<< HEAD
ouch

2021-11-05 09:24 UTC, sblondeau commented on database.sql
> +=======
aïe

2021-11-05 09:24 UTC, sblondeau commented on database.sql
> +>>>>>>> newdev2
ouille

2021-11-05 09:24 UTC, sblondeau commented on src/View/Cat/show.html.twig
> +{% block stylesheet %}<link rel="stylesheet" href="/assets/css/cards.css"><link rel="stylesheet" href="/assets/css/large-card.css"><link rel="stylesheet" href="/assets/css/cats.css">
fais des retours à la ligne entre chaque link

2021-11-05 09:24 UTC, sblondeau commented on public/assets/css/large-card.css
> +@media screen and (max-width:766px) {
vraiment utile cette media queries ?

2021-11-05 10:12 UTC, sblondeau requested changes
reste les fichier uploads à déversionner
faire un `git rm --cached -r public/uploads`

2021-11-05 10:12 UTC, sblondeau commented on src/View/Home/index.html.twig
> +	<link rel="stylesheet" href="/assets/css/cats.css"><link rel="stylesheet" href="/assets/css/cards.css">
retours à la ligne

2021-11-05 10:20 UTC, Djoasiong submitted a review, later dismissed

2021-11-08 09:48 UTC, Djoasiong approved these changes

2021-11-08 11:32 UTC, sblondeau approved these changes

2021-11-08 11:32 UTC, merged