S2 us07 3 fix spacing on cards
WildCodeSchool/orleans-202109-php-projet-apclo pull request #98
Opened 2021-11-08 10:31 UTC by WeisgerberEstelle

Adjust spacing between cards

2021-11-08 17:58 UTC, Djoasiong approved these changes

2021-11-09 07:54 UTC, sblondeau requested changes
je me re-retrouve avec les images uploadées ?!

2021-11-09 07:54 UTC, sblondeau commented on src/View/Home/index.html.twig
> +	{#{% include 'Home/_actualityBanner.html.twig' %}#}
pas de code commenté, si tu n'en a pas besoin, tu l'enlèves ;-)

2021-11-09 07:54 UTC, sblondeau commented on src/Controller/HomeController.php
> +            /*'article' => $article,*/
pas de code commenté

2021-11-09 15:44 UTC, ThibaultFoure approved these changes

2021-11-09 16:41 UTC, sblondeau submitted a review, later dismissed

2021-11-09 18:54 UTC, Djoasiong approved these changes

2021-11-09 21:26 UTC, sblondeau approved these changes

2021-11-09 21:26 UTC, merged