image size, responsive card, and displayed date changed
WildCodeSchool/orleans-202109-php-projet-apclo pull request #99
Opened 2021-11-08 18:49 UTC by WeisgerberEstelle

2021-11-08 18:56 UTC, Djoasiong approved these changes

2021-11-08 21:16 UTC, ThibaultFoure submitted a review, later dismissed

2021-11-09 08:00 UTC, sblondeau requested changes

2021-11-09 08:00 UTC, sblondeau commented on src/Model/CatManager.php
> +        $statement = $this->pdo->prepare("SELECT cat.name as name, image,
essaie de mieux m'écrire cette requete car en l'état elle est illisible.
Il faut que tu fasses tes retours à la ligne quand c'est pertinent (plutot qu'uniquement quand tu atteinds les 120 caractères).
Par ex, tu peux écrire
```sql
SELECT * FROM product p
    JOIN category c ON c.id = p.category_id
WHERE price>10
```
de plus tu peux omettre le "AS" et si tu veux le laisser (comme tous les mots clés mysql) met les en majuscule.

2021-11-09 08:01 UTC, sblondeau requested changes

2021-11-09 08:01 UTC, sblondeau commented on src/Model/CatManager.php
> +        ROUND((DATEDIFF(NOW(), birth_date) / 365)) as age,
et sinon tu peux je pense utiliser un DATE_FORMAT plutot pour avoir le nombre de year

2021-11-09 16:41 UTC, sblondeau approved these changes

2021-11-09 16:41 UTC, merged